# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd66a4a7c4873bdea62ef3f366e646742c7f7fd28327cc6a1ce4c5e7d20bf2c412af069482159973d3761b1455ad8d1e0f40f483c9eed3cf4a6ae359e94e0661

test:
  secret_key_base: a59a50997ae2a5f0744d0b22313af0b382812164a2ea08168dab8db91d95594b9bfe661a3073d1d5c3843cae83242f2bed2bd8c348fc26a214f8dab5ae4d1225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
